public enum Code {
    USER_PASS_INVALID,
    USER_REGISTERED,
    ALREADY_REGISTERED,
    USER_ALR_CONNECTED,
    PASS_NOT_CORRECT,
    USER_NOT_REGISTERED,
    USER_ALR_DISCONNECTED,
    ADD_FRIEND,
    ALREADY_FRIEND,
    FRIEND_NOT_ONLINE,
    SEND_REQUEST,
    NOT_FRIEND,
    OP_INVALID,
    FAILED,
    SUCCESS
}
